services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
      - ${SQL_FILE}:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      timeout: 5s
      retries: 10
    restart: always

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ${WP_ROOT}/wp-content:/var/www/html/wp-content:cached
      - ${WP_CONFIG}:/var/www/html/wp-config.php:cached
      - ${THEME_DIR}:/var/www/html/wp-content/themes/carcaj:cached
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
    restart: always

volumes:
  db_data: {}